export const allCourses = [
  { title: "Frontend Development", path: "/frontend-development-course" },
  { title: "Backend Development", path: "/backend-development" },
  { title: "Full Stack Web Development", path: "/fullstack-development" },
  { title: "MEAN Stack", path: "/mean-stack" },
  { title: "Digital Marketing", path: "/digital-marketing" },
 
  { title: "Python & Django Training", path: "/python-django" },
  { title: "QA Training", path: "/qa-training" },
  { title: "UI/UX Design Training", path: "/uiux-design" },
  { title: "Ethical Hacking Training", path: "/ethical-hacking" },
  { title: "Business Analysis Training", path: "/business-analysis" },
  { title: "Flutter App Development Training", path: "/flutter-training" },
  { title: "React Native App Development Training", path: "/react-native-training" },
  { title: "Python With Artificial Intelligence Training", path: "/python-ai-training" },
  { title: "Data Science With Python Training", path: "/data-science-python" },
  { title: "C & C++ Programming Language Training", path: "/c-cpp-training" },
  { title: "ASP.NET Core Training", path: "/aspnet-core" },
  { title: "React JS Training", path: "/reactjs-training" },
  { title: "Video Editing Training", path: "/video-editing" },
  { title: "AWS Solutions Architecture Training", path: "/aws-training" },
  { title: "Machine Learning With Python Training", path: "/ml-python" },
  { title: "Python Training", path: "/python-training" },
  { title: "DevOps Training", path: "/devops-training" },
  { title: "PHP Training", path: "/php-training" },
  { title: "SEO Basic Training", path: "/seo-basic" },
  { title: "SEO Advanced Training", path: "/seo-advanced" },
  { title: "NodeJs Training", path: "/nodejs-training" },
  { title: "ExpressJs Training", path: "/expressjs-training" },
];